/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx_using_properties_and_binding;

public class App {

    public static void main(String[] args) {
        new UsingChangeListenerApp().run();
    }
}
